# Generated by Django 6.0.6 on 2026-06-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('umbral_vibracion', models.FloatField(default=4.0)),
                ('umbral_inclinacion', models.FloatField(default=15.0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
