# Generated by Django 6.0.6 on 2026-06-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='icono',
            field=models.CharField(default='⚙️', max_length=10),
        ),
    ]
